name: Publish

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Prepare website directory
        run: |
          mkdir _site
          cp -r img _site/
          cp icons/* _site/

      - name: Install Asciidoctor
        run: |
          sudo chown -R $USER /var/lib/gems/
          sudo chown -R $USER /usr/local/bin
          gem install asciidoctor
        shell: bash

      - name: Render Docs
        run: asciidoctor ./*.asc -D _site/

      - name: Deploy documentationto GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site/
          enable_jekyll: false
          user_name: QubitPi
          user_email: jack20220723@gmail.com
          cname: anki.qubitpi.org
